# Простой Dockerfile для уже собранного приложения
FROM node:18-alpine

# Установка рабочей директории
WORKDIR /app

# Установка serve для раздачи статических файлов
RUN yarn global add serve

# Копирование собранного приложения
COPY public ./public

# Порт по умолчанию
ENV PORT=3000

# Expose порта
EXPOSE 3000

# Запуск приложения
CMD ["serve", "-s", "public", "-l", "3000"]
